Models/PaySlip.cs
namespace µPayroll.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Infrastructure;

    public class Payslip
    {
        public int Id { get; set; }

        /// <summary>
        /// Used to store datetime as tz agnostic timestamp
        /// </summary>
        internal long? DbIssuedAt
        {
            get => IssuedAt?.ToFileTimeUtc();
            set => IssuedAt = value.HasValue ? DateTime.FromFileTimeUtc(value.Value) : (DateTime?)null;
        }

        public DateTime? IssuedAt { get; set; }

        /// <summary>
        /// Calendar year
        /// </summary>
        [Required]
        [Range(2018, 2030)]
        public short Year { get; set; }

        /// <summary>
        /// Calendar month
        /// </summary>
        [Range(1, 12)]
        [Required]
        public byte Month { get; set; }

        [Required]
        //1185SD2
        [StringLength(7)]
        [Display(Name = "Tax code")]
        public string TaxCode { get; set; }


        [Required]
        [StringLength(1)]
        [Display(Name = "NI Category")]
        public NICategory NICategory { get; set; }

        /// <summary>
        /// Gross payment & any post tax deduction per sample Payslip
        /// </summary>
        public virtual IList<QuantitativeAdjustment> Payments { get; set; } = new List<QuantitativeAdjustment>();

        /// <summary>
        /// Statuary calculations affecting pay
        /// </summary>
        public virtual IList<Adjustment> Adjustments { get; set; } = new List<Adjustment>();

        public int EmployeeId { get; set; }

        public virtual Employee Employee { get; set; }
    }
}

Pages/Company/Delete.cshtml.cs
namespace µPayroll.Pages.Company
{
    using System.Threading.Tasks;
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using Models;

    public class DeleteModel : PageModel
    {
        readonly PayrollDbContext _context;

        public DeleteModel(PayrollDbContext context) => _context = context;

        [BindProperty] public Company Company { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Company = await _context.Companies.FindAsync(id);

            return Company == null ? (IActionResult) NotFound() : Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            Company = await _context.Companies.FindAsync(Company.Id);

            if (Company == null) return RedirectToPage("./Index");

            _context.Companies.Remove(Company);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Employee/Create.cshtml.cs
namespace µPayroll.Pages.Employee
{
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using Microsoft.EntityFrameworkCore;
    using Models;
    using System.Threading.Tasks;

    public class CreateModel : PageModel
    {
        readonly PayrollDbContext _context;

        public CreateModel(PayrollDbContext context) => _context = context;

        [BindProperty] public Employee Employee { get; set; } = new Employee { };

        public IActionResult OnGet(int companyId)
        {
            Employee.CompanyId = companyId;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            if (!await _context.Companies.AnyAsync(x => x.Id == Employee.CompanyId)) return NotFound();

            _context.Employees.Add(Employee);
            await _context.SaveChangesAsync();

            return RedirectToPage("../Company/Index");
        }
    }
}

Pages/Employee/Delete.cshtml.cs
namespace µPayroll.Pages.Employee
{
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using Microsoft.EntityFrameworkCore;
    using Models;
    using System.Threading.Tasks;

    public class DeleteModel : PageModel
    {
        readonly PayrollDbContext _context;

        public DeleteModel(PayrollDbContext context) => _context = context;

        [BindProperty] public Employee Employee { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Employee = await _context.Employees.SingleOrDefaultAsync(m => m.Id == id);

            return Employee == null ? (IActionResult)NotFound() : Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            Employee = await _context.Employees.SingleOrDefaultAsync(x => x.Id == Employee.Id);

            if (Employee == null) return NotFound();

            _context.Employees.Remove(Employee);
            await _context.SaveChangesAsync();

            return RedirectToPage("../Company/Index");
        }
    }
}

Pages/Employee/Details.cshtml.cs
namespace µPayroll.Pages.Employee
{
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using Microsoft.EntityFrameworkCore;
    using Models;
    using System.Threading.Tasks;

    public class DetailsModel : PageModel
    {
        readonly PayrollDbContext _context;

        public DetailsModel(PayrollDbContext context) => _context = context;

        [BindProperty] public Employee Employee { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Employee = await _context.Employees.Include(x => x.Address)
                .Include(x => x.Payslips)
                .SingleOrDefaultAsync(m => m.Id == id);

            return Employee == null ? (IActionResult)NotFound() : Page();
        }
    }
}

Pages/Payslip/Create.cshtml.cs
namespace µPayroll.Pages.Payslip
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Cedita.Payroll;
    using Cedita.Payroll.Engines.NationalInsurance;
    using Cedita.Payroll.Engines.Paye;
    using Data;
    using Infrastructure;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using Models;

    public class CreateModel : PageModel
    {
        readonly PayrollDbContext _context;
        readonly Func<int, IPayeCalculationEngine> _getPayeeEngineForYear;
        readonly Func<int, INiCalculationEngine> _getNiEngineForYear;

        public CreateModel(PayrollDbContext context, Func<int, IPayeCalculationEngine> getPayeeEngineForYear, Func<int, INiCalculationEngine> getNiEngineForYear)
        {
            _context = context;
            _getPayeeEngineForYear = getPayeeEngineForYear;
            _getNiEngineForYear = getNiEngineForYear;
        }

        public IList<SelectListItem> NICategories { get; } = Enum.GetNames(typeof(NICategory))
            .Select(x => new SelectListItem(x, x, x == NICategory.A.ToString())).ToArray();

        public string EmployeeName { get; set; }

        [BindProperty]
        public Payslip Payslip { get; set; } = new Payslip();

        public async Task<IActionResult> OnGetAsync(int id)
        {
            var employee = await _context.Employees.SingleOrDefaultAsync(x => x.Id == id);

            if (employee == null) return NotFound();

            var lastPayslip = await _context.Payslips.Where(x => x.EmployeeId == id).OrderByDescending(x => x.Year)
                .ThenBy(x => x.Month).FirstOrDefaultAsync();

            EmployeeName = employee.Name;
            Payslip.EmployeeId = id;

            var taxPeriod = lastPayslip == null
                ? DateTime.Today
                : new DateTime(lastPayslip.Year, lastPayslip.Month, 1).AddMonths(1);

            Payslip.Month = (byte)taxPeriod.Month;
            Payslip.Year = (short)taxPeriod.Year;
            Payslip.TaxCode = lastPayslip?.TaxCode;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var employee = await _context.Employees.SingleOrDefaultAsync(x => x.Id == Payslip.EmployeeId);

            if (employee == null) return NotFound();

            //Add default adjustments & payments
            Payslip.Adjustments = new List<Adjustment>
            {
                new Adjustment {Description = "SSP", AdjustmentType = AdjustmentType.StatuaryAddition},
                new Adjustment {Description = "SMP", AdjustmentType = AdjustmentType.StatuaryAddition},
                new Adjustment {Description = "OSPP", AdjustmentType = AdjustmentType.StatuaryAddition},
                new Adjustment {Description = "ASPP", AdjustmentType = AdjustmentType.StatuaryAddition},
                new Adjustment {Description = "SAP", AdjustmentType = AdjustmentType.StatuaryAddition},
                new Adjustment {Description = "Other", AdjustmentType = AdjustmentType.StatuaryAddition},

                new Adjustment {Description = "PAYE Tax", AdjustmentType = AdjustmentType.StatuaryDeduction, Value = _getPayeeEngineForYear(Payslip.Year).CalculateTaxDueForPeriod(Payslip.TaxCode, employee.AnnualSalary/12, PayPeriods.Monthly, 1)},
                new Adjustment {Description = "Employee's NI", AdjustmentType = AdjustmentType.StatuaryDeduction, Value = _getNiEngineForYear(Payslip.Year).CalculateNationalInsurance(employee.AnnualSalary/12, char.Parse(Payslip.NICategory.ToString()), PayPeriods.Monthly).EmployeeNi },
                new Adjustment {Description = "SLR", AdjustmentType = AdjustmentType.StatuaryDeduction},
                new Adjustment {Description = "AOE", AdjustmentType = AdjustmentType.StatuaryDeduction},
                new Adjustment {Description = "Pension", AdjustmentType = AdjustmentType.StatuaryDeduction},
                new Adjustment {Description = "Other", AdjustmentType = AdjustmentType.StatuaryDeduction}
            };

            Payslip.Payments = new List<QuantitativeAdjustment> { new QuantitativeAdjustment { Description = "Payment", UnitValue = employee.AnnualSalary / 12, Quantity = 1 } };

            _context.Payslips.Add(Payslip);

            await _context.SaveChangesAsync();

            return RedirectToPage("Details", new { id = Payslip.Id });
        }
    }
}

Pages/Payslip/Delete.cshtml.cs
namespace µPayroll.Pages.Payslip
{
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using Microsoft.EntityFrameworkCore;
    using Models;
    using System.Threading.Tasks;

    public class DeleteModel : PageModel
    {
        readonly PayrollDbContext _context;

        public DeleteModel(PayrollDbContext context) => _context = context;

        [BindProperty] public Payslip Payslip { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Payslip = await _context.Payslips.Include(x => x.Employee).SingleOrDefaultAsync(m => m.Id == id);

            return Payslip == null ? (IActionResult)NotFound() : Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            _context.Payslips.Remove(Payslip);

            await _context.SaveChangesAsync();

            return RedirectToPage("../Employee/Details", new { id = Payslip.EmployeeId });
        }
    }
}

Pages/Payslip/Details.cshtml.cs
namespace µPayroll.Pages.Payslip
{
    using System.Threading.Tasks;
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using Microsoft.EntityFrameworkCore;
    using Models;

    public class DetailsModel : PageModel
    {
        readonly PayrollDbContext _context;

        public DetailsModel(PayrollDbContext context) => _context = context;

        public string EmployeeName { get; set; }

        public bool IsReadOnly => Payslip.IssuedAt.HasValue;

        public Payslip Payslip { get; set; }

        [BindProperty]
        public QuantitativeAdjustment CurrentPayment { get; set; }

        [BindProperty]
        public Adjustment CurrentAdjustment { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Payslip = await _context.Payslips
                .Include(x => x.Adjustments)
                .Include(x => x.Payments)
                .Include(x => x.Employee)
                .SingleOrDefaultAsync(x => x.Id == id);

            if (Payslip == null) return NotFound();

            EmployeeName = Payslip.Employee.Name;

            return Page();
        }


        public async Task<IActionResult> OnGetNewPayment(int id)
        {
            if (!await _context.Payslips.AnyAsync(x => x.Id == id)) return NotFound();

            _context.QuantitativeAdjustments.Add(new QuantitativeAdjustment { PayslipPaymentId = id });
            await _context.SaveChangesAsync();

            return RedirectToPage(new { id });
        }

        public async Task<IActionResult> OnPostDiscardPaymentAsync()
        {
            if (!await _context.QuantitativeAdjustments.AnyAsync(x => x.Id == CurrentPayment.Id)) return NotFound();

            _context.QuantitativeAdjustments.Remove(CurrentPayment);
            await _context.SaveChangesAsync();

            return RedirectToPage(new { id = CurrentPayment.PayslipPaymentId });
        }

        public async Task<IActionResult> OnPostUpdatePaymentAsync()
        {
            if (!await _context.QuantitativeAdjustments.AnyAsync(x => x.Id == CurrentPayment.Id)) return NotFound();

            _context.QuantitativeAdjustments.Update(CurrentPayment);
            await _context.SaveChangesAsync();

            return RedirectToPage(new { id = CurrentPayment.PayslipPaymentId });
        }

        public async Task<IActionResult> OnGetNewAdjustment(int id)
        {
            if (!await _context.Payslips.AnyAsync(x => x.Id == id)) return NotFound();

            _context.Adjustments.Add(new Adjustment { PayslipAdjustmentId = id });
            await _context.SaveChangesAsync();

            return RedirectToPage(new { id });
        }

        public async Task<IActionResult> OnPostDiscardAdjustmentAsync()
        {
            if (!await _context.Adjustments.AnyAsync(x => x.Id == CurrentAdjustment.Id)) return NotFound();

            _context.Adjustments.Remove(CurrentAdjustment);
            await _context.SaveChangesAsync();

            return RedirectToPage(new { id = CurrentAdjustment.PayslipAdjustmentId });
        }

        public async Task<IActionResult> OnPostUpdateAdjustmentAsync()
        {
            if (!await _context.Adjustments.AnyAsync(x => x.Id == CurrentAdjustment.Id)) return NotFound();

            _context.Adjustments.Update(CurrentAdjustment);
            await _context.SaveChangesAsync();

            return RedirectToPage(new { id = CurrentAdjustment.PayslipAdjustmentId });
        }

    }
}

Pages/Payslip/Create.cshtml
@page
@model CreateModel

@{
    ViewData["Title"] = "Payslip Setup";
}

<div class="card border-dark card-limits">
    <form method="post">

        <input type="hidden" asp-for="Payslip.EmployeeId" />

        <div class="card-title bg-primary text-light card-header d-flex">
            <h4 class="m-auto">Payslip Setup For @Model.EmployeeName</h4>
        </div>

        <div class="card-body">
            <div class="form-group form-inline">
                <label asp-for="Payslip.Month"></label>
                <input class="form-control" asp-for="Payslip.Month" />
                <span asp-validation-for="Payslip.Month"></span>
            </div>
            <div class="form-group form-inline">
                <label asp-for="Payslip.Year"></label>
                <input class="form-control" asp-for="Payslip.Year" />
                <span asp-validation-for="Payslip.Year"></span>
            </div>
            <div class="form-group form-inline">
                <label asp-for="Payslip.TaxCode"></label>
                <input class="form-control" asp-for="Payslip.TaxCode" />
                <span asp-validation-for="Payslip.TaxCode"></span>
            </div>
            
            <div class="form-group form-inline">
                <label asp-for="Payslip.NICategory"></label>
                <select class="form-control" asp-for="Payslip.NICategory" asp-items="Model.NICategories"></select>
                <span asp-validation-for="Payslip.NICategory"></span>
            </div>
        </div>

        <div class="card-footer d-flex justify-content-end">
            <a asp-page="../Employee/Details" asp-route-id="@Model.Payslip.EmployeeId" class="btn btn-outline-dark">
                <i class="fas fa-backspace"></i>
                Cancel
            </a>
            <button class="ml-2 btn btn-primary">
                <i class="far fa-save"></i>
                Save
            </button>
        </div>

    </form>
</div>


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Pages/Payslip/Delete.cshtml
@page
@model DeleteModel

@{
    ViewData["Title"] = "Delete Employee";
}

<div class="m-auto">

    <h3 class="text-danger">Are you sure you want to delete payslip <span class="text-primary">@Model.Payslip.Year - @Model.Payslip.Month</span>
        for <span class="text-info">@Model.Payslip.Employee.Name</span> and remove all related data?</h3>

    <form method="post">
        <input type="hidden" asp-for="Payslip.Id" />
        <input type="hidden" asp-for="Payslip.EmployeeId" />

        <a asp-page="../Employee/Details" asp-route-id="@Model.Payslip.EmployeeId" class="btn btn-primary">
            <i class="fas fa-backspace"></i>
            Cancel
        </a>
        <button class="btn btn-danger ml-2">
            <i class="far fa-trash-alt"></i>
            Delete
        </button>
    </form>
</div>

Pages/Payslip/Details.cshtml
@page
@using µPayroll.Infrastructure
@model DetailsModel

@{
    ViewData["Title"] = "Payslip Details";
}

<div class="card border-dark card-limits">
    <div class="card-title bg-primary text-light card-header">
        <h4 class="text-center">Payslip Details For <span class="font-weight-bold">@Model.EmployeeName</span></h4>
    </div>

    <div class="card-body">
        <div class="d-flex rounded border py-2 bg-dark">
            <div class="flex-fill text-center">
                <label class="text-light" asp-for="Payslip.Month"></label>
                <div class="text-info">@Model.Payslip.Month</div>
            </div>
            <div class="flex-fill text-center">
                <label class="text-light" asp-for="Payslip.Year"></label>
                <div class="text-info">@Model.Payslip.Year</div>
            </div>
            <div class="flex-fill text-center">
                <label class="text-light" asp-for="Payslip.TaxCode"></label>
                <div class="text-info">@Model.Payslip.TaxCode</div>
            </div>
            <div class="flex-fill text-center">
                <label class="text-light" asp-for="Payslip.NICategory"></label>
                <div class="text-info">@Model.Payslip.NICategory</div>
            </div>
        </div>

        <div class="d-flex mt-3">
            <h4 class="text-secondary my-auto">Payments</h4>

            @if (!Model.IsReadOnly)
            {
                <a asp-page-handler="NewPayment" asp-route-id="@Model.Payslip.Id"
                   class="btn btn-link btn-primary border-0">
                    <span class="sr-only">New Payment</span>
                    <i class="far fa-plus-square"></i>
                </a>
            }
        </div>

        <div class="mt-2">
            @{
                <div class="row">
                    <div class="col-4">
                        @Html.DisplayNameFor(x => x.Payslip.Payments[0].Description)
                    </div>
                    <div class="col-2">
                        @Html.DisplayNameFor(x => x.Payslip.Payments[0].Quantity)
                    </div>
                    <div class="col-2">
                        @Html.DisplayNameFor(x => x.Payslip.Payments[0].UnitValue)
                    </div>
                    <div class="col-2">
                        @Html.DisplayNameFor(x => x.Payslip.Payments[0].Value)
                    </div>
                    <div class="col-2">
                    </div>
                </div>

                foreach (var CurrentPayment in Model.Payslip.Payments)
                {
                    if (!Model.IsReadOnly)
                    {
                        <form method="post">
                            <input type="hidden" asp-for="CurrentPayment.Id" value="@CurrentPayment.Id" />
                            <input type="hidden" asp-for="CurrentPayment.PayslipPaymentId" value="@CurrentPayment.PayslipPaymentId" />
                            <div class="row my-2">
                                <div class="col-4">
                                    <input class="form-control" asp-for="@CurrentPayment.Description" />
                                    <span asp-validation-for="@CurrentPayment.Description"></span>
                                </div>
                                <div class="col-2">
                                    <input class="form-control" asp-for="@CurrentPayment.Quantity" />
                                    <span asp-validation-for="@CurrentPayment.Quantity"></span>
                                </div>
                                <div class="col-2">
                                    <input class="form-control" asp-for="@CurrentPayment.UnitValue" />
                                    <span asp-validation-for="@CurrentPayment.UnitValue"></span>
                                </div>
                                <div class="col-2">
                                    <div class="form-control">@CurrentPayment.Value.ToString("c")</div>
                                </div>
                                <div class="col-2">
                                    <button asp-page-handler="DiscardPayment" asp-route-id="@Model.Payslip.Id" class="btn-outline-secondary btn">
                                        <span class="sr-only">Discard</span>
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                    <button asp-page-handler="UpdatePayment" asp-route-id="@Model.Payslip.Id" class="btn-primary btn border-0">
                                        <span class="sr-only">Save</span>
                                        <i class="far fa-save"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    }
                    else
                    { <div class="row">
                            <div class="col">
                                <label class="text-muted my-auto" asp-for="@CurrentPayment.Description"></label>
                                <input class="form-control" asp-for="@CurrentPayment.Description" />
                                <span asp-validation-for="@CurrentPayment.Description"></span>
                            </div>
                            <div class="col">
                                <label class="text-muted my-auto" asp-for="@CurrentPayment.Quantity"></label>
                                <input class="form-control" asp-for="@CurrentPayment.Quantity" />
                                <span asp-validation-for="@CurrentPayment.Quantity"></span>
                            </div>
                            <div class="col">
                                <label class="text-muted my-auto" asp-for="@CurrentPayment.UnitValue"></label>
                                <input class="form-control" asp-for="@CurrentPayment.UnitValue" />
                                <span asp-validation-for="@CurrentPayment.UnitValue"></span>
                            </div>
                            <div class="col">
                                <label class="text-muted my-auto" asp-for="@CurrentPayment.Value"></label>
                                <div>@CurrentPayment.Value</div>
                            </div>
                        </div>
                    }
                }
            }
        </div>

        <div class="d-flex mt-3">
            <h4 class="text-secondary my-auto">Adjustments</h4>

            @if (!Model.IsReadOnly)
            {
                <a asp-page-handler="NewAdjustment" asp-route-id="@Model.Payslip.Id"
                   class="btn btn-link btn-primary border-0">
                    <span class="sr-only">New Payment</span>
                    <i class="far fa-plus-square"></i>
                </a>
            }
        </div>

        <div class="mt-2 d-flex flex-row flex-wrap">
            @{
                if (!Model.IsReadOnly)
                {
                    <div class="flex-fill p-2 m-1">
                        <h5 class="text-center text-black-50">Statuary Additions</h5>
                        <div class="row text-info text-center">
                            <div class="col-6">
                                Description
                            </div>
                            <div class="col-4">
                                Value
                            </div>
                            <div class="col-2">
                            </div>
                        </div>
                        @foreach (var CurrentAdjustment in Model.Payslip.Adjustments.Where(x => x.AdjustmentType == AdjustmentType.StatuaryAddition))
                        {
                            <form method="post">
                                <input type="hidden" asp-for="CurrentAdjustment.Id" value="@CurrentAdjustment.Id" />
                                <input type="hidden" asp-for="CurrentAdjustment.PayslipAdjustmentId" value="@CurrentAdjustment.PayslipAdjustmentId" />
                                <div class="row my-1">
                                    <div class="col-6">
                                        <input class="form-control" asp-for="@CurrentAdjustment.Description" />
                                        <span asp-validation-for="@CurrentAdjustment.Description"></span>
                                    </div>
                                    <div class="col-4">
                                        <input class="form-control" asp-for="@CurrentAdjustment.Value" />
                                        <span asp-validation-for="@CurrentAdjustment.Value"></span>
                                    </div>
                                    <div class="col-2">
                                        <button asp-page-handler="DiscardAdjustment" asp-route-id="@Model.Payslip.Id" class="btn-outline-secondary btn">
                                            <span class="sr-only">Discard</span>
                                            <i class="far fa-trash-alt"></i>
                                        </button>
                                        <button asp-page-handler="UpdateAdjustment" asp-route-id="@Model.Payslip.Id" class="btn-primary btn border-0">
                                            <span class="sr-only">Save</span>
                                            <i class="far fa-save"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        }
                    </div>
                    <div class="flex-fill p-2 m-1">
                        <h5 class="text-center text-black-50">Statuary Deductions</h5>
                        <div class="row text-info text-center">
                            <div class="col-6">
                                Description
                            </div>
                            <div class="col-4">
                                Value
                            </div>
                            <div class="col-2">
                            </div>
                        </div>
                        @foreach (var CurrentAdjustment in Model.Payslip.Adjustments.Where(x => x.AdjustmentType == AdjustmentType.StatuaryDeduction))
                        {
                            <form method="post">
                                <input type="hidden" asp-for="CurrentAdjustment.Id" value="@CurrentAdjustment.Id" />
                                <input type="hidden" asp-for="CurrentAdjustment.PayslipAdjustmentId" value="@CurrentAdjustment.PayslipAdjustmentId" />
                                <div class="row my-1">
                                    <div class="col-6">
                                        <input class="form-control" asp-for="@CurrentAdjustment.Description" />
                                        <span asp-validation-for="@CurrentAdjustment.Description"></span>
                                    </div>
                                    <div class="col-4">
                                        <input class="form-control" asp-for="@CurrentAdjustment.Value" />
                                        <span asp-validation-for="@CurrentAdjustment.Value"></span>
                                    </div>
                                    <div class="col-2">
                                        <button asp-page-handler="DiscardAdjustment" asp-route-id="@Model.Payslip.Id" class="btn-outline-secondary btn">
                                            <span class="sr-only">Discard</span>
                                            <i class="far fa-trash-alt"></i>
                                        </button>
                                        <button asp-page-handler="UpdateAdjustment" asp-route-id="@Model.Payslip.Id" class="btn-primary btn border-0">
                                            <span class="sr-only">Save</span>
                                            <i class="far fa-save"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        }
                    </div>
                }
            }
        </div>

    </div>

    <div class="card-footer text-right">
        <a asp-page="../Employee/Details" asp-route-id="@Model.Payslip.EmployeeId" class="btn btn-outline-dark">
            <i class="fas fa-backspace"></i>
            Back
        </a>
        @if (!Model.IsReadOnly)
        {
            <a asp-page-handler="IssuePayslip" asp-route-id="@Model.Payslip.Id" class="ml-2 btn btn-primary text-light">
                <i class="fas fa-lock"></i>
                Issue Payslip
            </a>
        }
    </div>
</div>